name: "Imagens por commit"

on:
  push:
    branches: [ "**", "!master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ritinhauwu
          password: ${{ secrets.ACTIONS_MAKE_PACKAGES }}

      - uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/ritinhauwu/civisafe-backend:${{ github.sha }}

      - uses: docker/build-push-action@v5
        with:
          context: ./frontend
          build-args: |
            COMMIT_SHA=${{ github.sha }}
          push: true
          tags: ghcr.io/ritinhauwu/civisafe-frontend:${{ github.sha }}